UDP_MTU = 65535

CHAN_ID_SIZE = 2

MIN_CHAN_ID = 1
MAX_CHAN_ID = 2**(8*CHAN_ID_SIZE)-1

MIN_PORT = 50000
MAX_PORT = 60000

REPLAY_WINDOW_SIZE = 10

CTR_PREFIX_LEN = 8
SYM_KEY_LEN = 16

ASYM_OUTPUT_LEN = 256
ASYM_INPUT_LEN = 210
ASYM_PADDING_LEN = ASYM_OUTPUT_LEN - ASYM_INPUT_LEN

CTR_MODE_PADDING = CTR_PREFIX_LEN

IPV4_LEN = 4
PORT_LEN = 2
