#!/bin/bash

IP=127.0.0.1

ENTRY_POINT_PORT=20000

MIX_INDEX=1
MIX_PORT=20001

TERMINAL=xterm
TERM_OPS="-e"

if type xfce4-terminal; then
    TERMINAL=xfce4-terminal
    TERM_OPS="-H -e"
fi

# start entry point
$TERMINAL -T EntryPoint.py $TERM_OPS "./EntryPoint.py $IP:$ENTRY_POINT_PORT config/MixChain.cfg" &

# start mixes 
for cfg_file in config/Mix[0-9]*.cfg; do
    $TERMINAL -T "Mix.py $MIX_INDEX" $TERM_OPS "./Mix.py $cfg_file"
    : $((MIX_INDEX++))
done 

# start exit point
RECV_PORT=20004
$TERMINAL -T ExitPoint.py $TERM_OPS "./ExitPoint.py $IP:$RECV_PORT" &

if [ -n "$1" ]; then
    $TERMINAL -T "Recv.py 40000" $TERM_OPS "./Recv.py $IP:40000" &
    PYTHONSTARTUP=startupfile python3 &
fi
