from typing import List

from Crypto.Cipher import AES

from Ciphers.Cipher import Cipher

def default_cipher(keys: List[bytes], iv: bytes) -> CBC: ...
def gen_key() -> bytes: ...
def gen_iv() -> bytes: ...


class CBC(Cipher):
    iv_size: int

    @staticmethod
    def gen_iv(length: int) -> bytes: ...
    @staticmethod
    def gen_key() -> bytes: ...

    def __init__(self, encryptors: List[AES], decryptors: List[AES], iv_size: int):
        super().__init__(encryptors, decryptors)
        ...
    def decrypt(self, data: bytes) -> bytes: ...
    def encrypt(self, data: bytes) -> bytes: ...
    def encrypt_with_data(self, plain_text: bytes, additional_data: List[bytes]) -> bytes: ...