from typing import List
from Crypto.Cipher import AES


class Cipher:
    encryptors: List[AES]
    decryptors: List[AES]
    stages: int
    def __init__(self, encryptors: List[AES], decryptors: List[AES]): ...
    def decrypt(self, data: bytes) -> bytes: ...
    def encrypt(self, data: bytes) -> bytes: ...
    def prepare_data(self, data: bytes) -> bytes: ...
    def finalize_data(self, data: bytes) -> bytes: ...
    def encrypt_with_data(self, plain_text: bytes, additional_data: List) -> bytes: ...


def default_cipher(keys: List[bytes], iv: int) -> Cipher: ...
def gen_iv() -> bytes: ...
