from typing import Union


class SHA1Hash(object):
    digest_size: int
    block_size: int
    oid: str
    def __init__(self, data: Union[ bytes, bytearray, memoryview]) -> None: ...
    def update(self, data: Union[ bytes, bytearray, memoryview]) -> None: ...
    def digest(self) -> bytes: ...
    def hexdigest(self) -> str: ...
    def copy(self) -> SHA1Hash: ...
    def new(self, data: Union[ bytes, bytearray, memoryview]) -> SHA1Hash: ...

def new(data: Union[ bytes, bytearray, memoryview]) -> SHA1Hash: ...

digest_size: int
block_size: int
