from typing import Union


class SHA512Hash(object):
    block_size: int
    digest_size: int
    oid: str
    def __init__(self, data: Union[bytes, bytearray, memoryview], truncate: int) -> None: ...
    def update(self, data: Union[bytes, bytearray, memoryview]) -> None: ...
    def digest(self) -> bytes: ...
    def hexdigest(self) -> str: ...
    def copy(self) -> SHA512Hash: ...
    def new(self, data: Union[bytes, bytearray, memoryview]) -> SHA512Hash: ...

def new(data: Union[bytes, bytearray, memoryview], truncate: int): ...

digest_size: int
block_size: int
