from typing import Union


class SHAKE256_XOF(object):
    oid: str
    def __init__(self, data: Union[bytes, bytearray, memoryview]) -> None: ...
    def update(self, data: Union[bytes, bytearray, memoryview]) -> SHAKE256_XOF: ...
    def read(self, length: int) -> bytes: ...
    def new(self, data: Union[bytes, bytearray, memoryview]) -> SHAKE256_XOF: ...

def new(data: Union[bytes, bytearray, memoryview]) -> SHAKE256_XOF: ...
