from typing import Union


class SHAKE128_XOF(object):
    oid: str
    def __init__(self, data: Union[bytes, bytearray, memoryview]) -> None: ...
    def update(self, data: Union[bytes, bytearray, memoryview]) -> SHAKE128_XOF: ...
    def new(self, data: Union[bytes, bytearray, memoryview]) -> SHAKE128_XOF: ...

def new(data: Union[bytes, bytearray, memoryview]) -> SHAKE128_XOF: ...
